spring:
  profiles:
    active: '@spring.profiles.active@'
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/students
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:123}
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  liquibase:
    change-log: classpath:migrationdb/master.xml
logging:
  level:
    root: info