spring:
  profiles:
    active: '@spring.profiles.active@'
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/students
    username: postgres
    password: 123
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    root: info
